### ISSUE TITLE
Create Unit Tests for the EmployeeRepository Class of Stored Procedures

### ISSUE THREAD

**Issue by sohlae** [josh-monreal/repository-pattern#21]
# TASKS
- [ ] Create a Stored Procedures folder and create a Repositories folder inside it
- [ ] Create a class named `EmployeeRepositoryTests`

### Add Method
- [ ] When the method is called, then verify that the `Add` method of the Context class has been called once.
- [ ] When the method is called, then verify that the stored procedure named `sp_InsertEmployee` is called once.
